// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/25/2024, 10:51:19 AM
const configMerger = require("/home/gsavic/projects/goran/kinderguard/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/gsavic/projects/goran/kinderguard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/plugins/**/*.{js,ts,mjs}","/home/gsavic/projects/goran/kinderguard/composables/**/*.{js,ts,mjs}","/home/gsavic/projects/goran/kinderguard/utils/**/*.{js,ts,mjs}","/home/gsavic/projects/goran/kinderguard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gsavic/projects/goran/kinderguard/app.config.{js,ts,mjs}"] }));

module.exports = config
